using System;
using System.Collections.Generic;
using System.Linq;

namespace Pandell
{
    class Program
    {
        static void Main(string[] args)
        {

            //Initialize list with number starting from 1 to 10 000 this will be unique
            IEnumerable<int> numList = Enumerable.Range(1, 10000);

            Random rnd = new Random();

            //Randomize it using linq. Create a temporary object to allow for storage of order which is randomly generated by the random generator. Then use linq to sort it.
            //Convert it to a list of integer afterwards
            List<int> randList = numList.Select(x => new {val = x, order = rnd.Next()}).OrderBy(x => x.order).Select(x=> x.val).ToList();

            foreach (var i in randList)
            {
                Console.WriteLine(i);
            }


        }
    }
}
